// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination=./mocks/transaction_mock.go -source=transaction.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "go-pismo-challenge/pkg/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionConnector is a mock of TransactionConnector interface.
type MockTransactionConnector struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionConnectorMockRecorder
	isgomock struct{}
}

// MockTransactionConnectorMockRecorder is the mock recorder for MockTransactionConnector.
type MockTransactionConnectorMockRecorder struct {
	mock *MockTransactionConnector
}

// NewMockTransactionConnector creates a new mock instance.
func NewMockTransactionConnector(ctrl *gomock.Controller) *MockTransactionConnector {
	mock := &MockTransactionConnector{ctrl: ctrl}
	mock.recorder = &MockTransactionConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionConnector) EXPECT() *MockTransactionConnectorMockRecorder {
	return m.recorder
}

// CheckIdempotency mocks base method.
func (m *MockTransactionConnector) CheckIdempotency(ctx context.Context, trxUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIdempotency", ctx, trxUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckIdempotency indicates an expected call of CheckIdempotency.
func (mr *MockTransactionConnectorMockRecorder) CheckIdempotency(ctx, trxUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIdempotency", reflect.TypeOf((*MockTransactionConnector)(nil).CheckIdempotency), ctx, trxUUID)
}

// Create mocks base method.
func (m *MockTransactionConnector) Create(ctx context.Context, a model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransactionConnectorMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionConnector)(nil).Create), ctx, a)
}
